# Generated by Django 5.2.6 on 2025-09-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_post_poster_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='repost_id',
        ),
        migrations.AddField(
            model_name='post',
            name='repost_id',
            field=models.ManyToManyField(blank=True, related_name='repost', to='mainapp.post'),
        ),
    ]
