# Generated by Django 5.2.6 on 2025-09-27 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_post_repost_id_post_repost_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='repost_id',
        ),
        migrations.AddField(
            model_name='post',
            name='repost_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repost', to='mainapp.post'),
        ),
    ]
