# Generated by Django 5.2.6 on 2025-09-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_post_repost_id_post_repost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
